/**
 * 错误枚举
 */
export enum ErrorCodeEnum {
  'NOT_FOUND' = 'NOT_FOUND',
  'ARGUMENUT_ERROR' = 'ARGUMENUT_ERROR',
  'ARGUMENUT_TYPE_ERROR' = 'ARGUMENUT_TYPE_ERROR',
  'REQUIRED_ARGUMENUT' = 'REQUIRED_ARGUMENUT',
  'PERMISSION_DENIED' = 'PERMISSION_DENIED',
  'NEED_LOGIN' = 'NEED_LOGIN',
  'EXSIT_DATA' = 'EXSIT_DATA',
}
